version: '3.8'
services:
  frontend:
    user: root
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    volumes:
      - ./client/doc-manager:/app
    working_dir: /app
    ports:
      - "3000:3000"

  backend:
    user: root
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8001:8001"
