version: '3.8'
services:
  node:
    user: root
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    volumes:
      - ./client/doc-manager:/app
    working_dir: /app
    ports:
      - "3000:3000"

  prod:
    user: root
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8001:8001"
