# Generated by Django 4.1.9 on 2023-08-19 16:01

from django.db import migrations, models
import file_versions.models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="file",
            field=models.FileField(default="", upload_to=file_versions.models.generate_bin_path),
            preserve_default=False,
        ),
    ]
