# Generated by Django 4.1.9 on 2023-08-19 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_fileversion_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
